.\" Automatically generated by Pandoc 3.1.11
.\"
.TH "AsyncGenerator.throw" "JS" "September 25, 2023" "JavaScript" "JavaScript Reference Manual"
.SH NAME
AsyncGenerator.throw \- AsyncGenerator.prototype.throw()
.SH SYNOPSIS
The \f[B]\f[CB]throw()\f[B]\f[R] method of \f[CR]AsyncGenerator\f[R]
instances acts as if a \f[CR]throw\f[R] statement is inserted in the
generator\[cq]s body at the current suspended position, which informs
the generator of an error condition and allows it to handle the error,
or perform cleanup and close itself.
.SH SYNTAX
.IP
.EX
asyncGeneratorInstance.throw(exception)
.EE
.SS Parameters
.TP
\f[B]exception\f[R]
The exception to throw.
For debugging purposes, it is useful to make it an \f[CR]instanceof\f[R]
\f[CR]Error\f[R].
.SS Return value
If the thrown error is not caught, it will return a \f[CR]Promise\f[R]
which rejects with the exception passed in.
.PP
If the exception is caught by a \f[CR]try...catch\f[R] and the generator
resumes to yield more values, it will return a \f[CR]Promise\f[R] which
resolves with an \f[CR]Object\f[R] with two properties:
.TP
\f[B]done\f[R]
A boolean value:
.RS
.IP \[bu] 2
\f[CR]true\f[R] if the generator function\[cq]s control flow has reached
the end.
.IP \[bu] 2
\f[CR]false\f[R] if the generator function is able to produce more
values.
.RE
.TP
\f[B]value\f[R]
The value yielded from the next \f[CR]yield\f[R] expression.
.SH EXAMPLES
.SS Using throw()
The following example shows a simple generator and an error that is
thrown using the \f[CR]throw\f[R] method.
An error can be caught by a \f[CR]try...catch\f[R] block as usual.
.IP
.EX
// An async task. Pretend it\[aq]s doing something more useful
// in practice.
function sleep(time) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, time);
  });
}

async function* createAsyncGenerator() {
  while (true) {
    try {
      await sleep(500);
      yield 42;
    } catch (e) {
      console.error(e);
    }
  }
}

const asyncGen = createAsyncGenerator();
asyncGen.next(1).then((res) => console.log(res)); // { value: 42, done: false }
asyncGen
  .throw(new Error(\[dq]Something went wrong\[dq])) // Error: Something went wrong
  .then((res) => console.log(res)); // { value: 42, done: false }
.EE
.SH SEE ALSO
.IP \[bu] 2
\f[CR]async function*\f[R]
.IP \[bu] 2
Iterators and generators guide
